# Generated by Django 3.2.12 on 2022-03-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='time',
        ),
    ]
